/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;
import Modelo.Cliente;
import javax.swing.table.DefaultTableModel;

public class Panel_Clientes extends javax.swing.JPanel {

    DefaultTableModel modelo;

    public Panel_Clientes() {
        initComponents();
        modelo = (DefaultTableModel) clientes.getModel();
    }
/**
 *
 * @author jr245
 */

public void setTablaClientes(java.util.List<Modelo.Cliente> listaClientes) {
    modelo.setRowCount(0); // limpiar la tabla
    for (Modelo.Cliente c : listaClientes) {
        Object[] fila = {
            c.getClientes_id(),
            c.getNombre(),
            c.getApellido(),
            c.getEmail(),
            c.getTelefono()
        };
        modelo.addRow(fila);
    }
}

public void mostrarMensaje(String mensaje) {
    javax.swing.JOptionPane.showMessageDialog(this, mensaje);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        clientes = new javax.swing.JTable();

        setBackground(new java.awt.Color(0, 0, 0));

        clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Apellido", "Correo", "Telefono"
            }
        ));
        jScrollPane1.setViewportView(clientes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(242, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable clientes;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
