/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.BorderLayout;
import vista.Panel_Boletos;
import vista.Panel_Clientes;
import vista.Panel_Peliculas;
import vista.Panel_funciones;

/**
 *
 * @author jr245
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        panel_Principal = new javax.swing.JPanel();
        principal = new javax.swing.JLabel();
        btninicio = new javax.swing.JButton();
        btnpeliculas = new javax.swing.JButton();
        btncompras = new javax.swing.JButton();
        btnboletos = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(220, 38, 38));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sistema de Gestion De Cine", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Verdana", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 838, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 29, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 60));

        panel_Principal.setBackground(new java.awt.Color(102, 102, 102));
        panel_Principal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_Principal.setLayout(new java.awt.CardLayout());

        principal.setBackground(new java.awt.Color(255, 255, 255));
        principal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        principal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/Portada_DALI_Oberon_Grand_Vokal.png"))); // NOI18N
        principal.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Bienvenido", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        principal.setMaximumSize(new java.awt.Dimension(570, 400));
        principal.setMinimumSize(new java.awt.Dimension(570, 400));
        principal.setPreferredSize(new java.awt.Dimension(570, 400));
        panel_Principal.add(principal, "card2");

        jPanel1.add(panel_Principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 640, 450));

        btninicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/icons8-casa-16.png"))); // NOI18N
        btninicio.setText("Inicio");
        btninicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninicioActionPerformed(evt);
            }
        });
        jPanel1.add(btninicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 130, -1));

        btnpeliculas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/icons8-película-16.png"))); // NOI18N
        btnpeliculas.setText("Peliculas");
        btnpeliculas.setPreferredSize(new java.awt.Dimension(57, 23));
        btnpeliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpeliculasActionPerformed(evt);
            }
        });
        jPanel1.add(btnpeliculas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 130, -1));

        btncompras.setText("Funciones");
        btncompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncomprasActionPerformed(evt);
            }
        });
        jPanel1.add(btncompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 130, -1));

        btnboletos.setText("Boletos");
        btnboletos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnboletosActionPerformed(evt);
            }
        });
        jPanel1.add(btnboletos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 130, -1));

        jButton2.setText("Clientes");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 390, 130, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 844, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btninicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninicioActionPerformed
        panel_Principal.removeAll();
        panel_Principal.add(principal,BorderLayout.CENTER);
        panel_Principal.revalidate();
        panel_Principal.repaint();
        
        
    }//GEN-LAST:event_btninicioActionPerformed

    private void btnpeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpeliculasActionPerformed
        Panel_Peliculas p1 = new Panel_Peliculas();
          
        p1.setSize(640,450);
        p1.setLocation(0,0);
        panel_Principal.removeAll();
        panel_Principal.add(p1,BorderLayout.CENTER);
        panel_Principal.revalidate();
        panel_Principal.repaint();
        
        
    }//GEN-LAST:event_btnpeliculasActionPerformed

    private void btncomprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncomprasActionPerformed
        Panel_funciones p2 = new Panel_funciones();
          
        p2.setSize(640,450);
        p2.setLocation(0,0);
        panel_Principal.removeAll();
        panel_Principal.add(p2,BorderLayout.CENTER);
        panel_Principal.revalidate();
        panel_Principal.repaint();
    }//GEN-LAST:event_btncomprasActionPerformed

    private void btnboletosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnboletosActionPerformed
        Panel_Boletos p3 = new Panel_Boletos();
        
        p3.setSize(640,450);
        p3.setLocation(0,0);
        panel_Principal.removeAll();
        panel_Principal.add(p3,BorderLayout.CENTER);
        panel_Principal.revalidate();
        panel_Principal.repaint();
        
    }//GEN-LAST:event_btnboletosActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Panel_Clientes p4 = new Panel_Clientes();
        
        p4.setSize(640,450);
        p4.setLocation(0,0);
        panel_Principal.removeAll();
        panel_Principal.add(p4,BorderLayout.CENTER);
        panel_Principal.revalidate();
        panel_Principal.repaint();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnboletos;
    private javax.swing.JButton btncompras;
    private javax.swing.JButton btninicio;
    private javax.swing.JButton btnpeliculas;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panel_Principal;
    private javax.swing.JLabel principal;
    // End of variables declaration//GEN-END:variables
}
